### ISSUE TITLE
Vídeo Explicativo

### ISSUE THREAD

**Issue by darmsDD** [projeto-de-algoritmos/grafos1NomeDoProjeto#8]
## Descrição
Não há explicações sobre o projeto no vídeo, mostra apenas como rodar o projeto e mostra ele funcionando.

**Comment by senaarth** [comment]
Favor verificar a branch criada com o nome da issue atual, refiz o vídeo tentando explicando o máximo dentro dos 2 minutos de limite. @darmsDD
